package app

object DependenciesVersions {
    const val core_ktx_version = "1.2.0"
    const val kotlin_version = "1.5.21"
    const val appcompat_version = "1.3.1"
    const val material_design_version = "1.4.0"
    const val compose_version = "1.0.2"
    const val lifecycle_ktx_version = "2.3.1"
    const val compose_activity_version = "1.3.1"
    const val junit_version = "4.12"
    const val junit_ext_version = "1.1.3"
    const val espresso_version = "3.4.0"
    const val rx_android_version = "2.1.1"
    const val rxkotlin_version = "2.4.0"
    const val paging_version = "3.0.1"
    const val gson_version = "2.8.6"
    const val lifecycle_version = "2.2.0"
    const val paging_compose_version = "1.0.0-alpha13"
    const val swipe_refresh_version = "0.18.0"
    const val retrofit_version = "2.9.0"
    const val coil_version = "0.15.0"
    const val coil_compose_version = "1.3.2"
    const val okhttp_version = "4.9.1"
    const val room_version = "2.4.1"
}